### ISSUE TITLE
celery implementation for loss section

### ISSUE THREAD

**Issue by iamtekson** [ashokdahal/RiskChanges#13]

**Comment by shakyaanice** [comment]
Error in loss calculation
```
Traceback (most recent call last): File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc return self._engine.get_loc(casted_key) File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item KeyError: 'Flash flood' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task R = retval = fun(*args, **kwargs) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__ return self.run(*args, **kwargs) File "/opt/sdss/django/sdss/loss/tasks.py", line 116, in loss_calculation_with_celery loss_calculation(loss_id) File "/opt/sdss/django/sdss/loss/tasks.py", line 44, in loss_calculation ComputeLoss(CONN_STR, exposure_id, loss_id, loss_type) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeLoss.py", line 93, in ComputeLoss exposure = estimatevulnerability(exposure, haztype, vulnColumn, con) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeLoss.py", line 40, in estimatevulnerability for i in exposuretable[vulnColumn].unique(): File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__ indexer = self.columns.get_loc(key) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc raise KeyError(key) from err KeyError: 'Flash flood'
```

**Comment by shakyaanice** [comment]
Loss calculation error
```
Traceback (most recent call last): File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc return self._engine.get_loc(casted_key) File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item KeyError: 'Flash flood' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task R = retval = fun(*args, **kwargs) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__ return self.run(*args, **kwargs) File "/opt/sdss/django/sdss/loss/tasks.py", line 116, in loss_calculation_with_celery loss_calculation(loss_id) File "/opt/sdss/django/sdss/loss/tasks.py", line 44, in loss_calculation ComputeLoss(CONN_STR, exposure_id, loss_id, loss_type) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeLoss.py", line 93, in ComputeLoss exposure = estimatevulnerability(exposure, haztype, vulnColumn, con) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeLoss.py", line 40, in estimatevulnerability for i in exposuretable[vulnColumn].unique(): File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__ indexer = self.columns.get_loc(key) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc raise KeyError(key) from err KeyError: 'Flash flood'
```
