### ISSUE TITLE
exposure calculation error: "Float object is not iterable"

### ISSUE THREAD

**Issue by iamtekson** [ashokdahal/RiskChanges#33]
The complete error log is here:   
```
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/sdss/django/exposure/views.py", line 121, in create
    exposure_calculation(exposure_id)
  File "/opt/sdss/django/exposure/tasks.py", line 29, in exposure_calculation
    ComputeExposure(conn_str, ear_id, hazard_id, exposure_id, haz_file=haz_file)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/computeExposure.py", line 145, in ComputeExposure
    df = pointExposure(ear, haz, expid, Ear_Table_PK)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/computeExposure.py", line 113, in pointExposure
    coords = [(x, y) for x, y in zip(row.geom.x, row.geom.y)]

Exception Type: TypeError at /api/exposure/exposure/
Exception Value: 'float' object is not iterable
```

**Comment by iamtekson** [comment]
Just for the reference. Since the data is in the server, I have to update the code in the server. I will check this and close this issue, If it worked fine.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/39838116/130609597-16c2cb35-7891-4e7a-8a94-773a5f1b4085.png)

**Comment by iamtekson** [comment]
The error is still there: 

```
Traceback (most recent call last):
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/sdss/django/exposure/views.py", line 121, in create
    exposure_calculation(exposure_id)
  File "/opt/sdss/django/exposure/tasks.py", line 29, in exposure_calculation
    ComputeExposure(conn_str, ear_id, hazard_id, exposure_id, haz_file=haz_file)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/computeExposure.py", line 145, in ComputeExposure
    df = pointExposure(ear, haz, expid, Ear_Table_PK)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/computeExposure.py", line 115, in pointExposure
    df_temp['class'] = a
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/frame.py", line 3163, in __setitem__
    self._set_item(key, value)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/frame.py", line 3241, in _set_item
    self._ensure_valid_index(value)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/frame.py", line 3290, in _ensure_valid_index
    if not len(self.index) and is_list_like(value) and len(value):

Exception Type: TypeError at /api/exposure/exposure/
Exception Value: object of type 'generator' has no len()
Request information:
USER: gicadmin
```

**Comment by ashokdahal** [comment]
This might be because the co-ordinate system of both data in different systems, or the rasterio module gives back a object instead of values. I will check and update it by either adding try or changing rasterio.sample to something else.

**Comment by ashokdahal** [comment]
Solved by new update. please check. @iamtekson #

**Comment by ashokdahal** [comment]
Solved.
