### ISSUE TITLE
x is neither increasing nor decreasing error in risk calcualtion

### ISSUE THREAD

**Issue by iamtekson** [ashokdahal/RiskChanges#43]
I got this error on a single hazard risk calculation. On my second try, it worked successfully. Just added it for the reference.

```python
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeRisk.py", line 65, in ComputeRisk
    risk = calculateRisk(lossdf, columns, probs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeRisk.py", line 48, in calculateRisk
    aal = dutch_method(xx, yy)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeRisk.py", line 10, in dutch_method
    AAL = auc(yy, xx)+(xx[0]*yy[0])
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 97, in auc
    raise ValueError("x is neither increasing nor decreasing "

Exception Type: ValueError at /api/risk/
Exception Value: x is neither increasing nor decreasing : [0.005 0.02  0.01 ].
Request information:
USER: tek@ait.asia

```

**Comment by ashokdahal** [comment]
Solve by adding an exception in case of total zero or one, by adding zero in case of zero and in case of constant loss multiply with the inverse of the minimum return period of loss.

**Comment by iamtekson** [comment]
Still facing the same issue. It is happening when we try to calculate the risk of a hazard having vulnerability of `all_zero` and `all_one`. 

```python
Internal Server Error: /api/risk/
Traceback (most recent call last):
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/sdss/django/sdss/risk/views.py", line 106, in create
    risk_calculation(risk_id)
  File "/opt/sdss/django/sdss/risk/tasks.py", line 69, in risk_calculation
    ComputeRisk(CONN_STR, loss_id, risk_id)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeRisk.py", line 73, in ComputeRisk
    risk = calculateRisk(lossdf, columns, probs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeRisk.py", line 56, in calculateRisk
    aal = dutch_method(xx, yy)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeRisk.py", line 15, in dutch_method
    AAL = auc(yy, xx)+(xx[0]*yy[0])
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 97, in auc
    raise ValueError("x is neither increasing nor decreasing "
ValueError: x is neither increasing nor decreasing : [0.02 0.1  0.01].
```

**Comment by shakyaanice** [comment]
Issue still persists for single hazard risk calculation.

```
Traceback (most recent call last): File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task R = retval = fun(*args, **kwargs) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__ return self.run(*args, **kwargs) File "/opt/sdss/django/sdss/risk/tasks.py", line 143, in risk_calculation_with_celery risk_calculation(risk_id) File "/opt/sdss/django/sdss/risk/tasks.py", line 69, in risk_calculation ComputeRisk(CONN_STR, loss_id, risk_id) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeRisk.py", line 73, in ComputeRisk risk = calculateRisk(lossdf, columns, probs) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeRisk.py", line 56, in calculateRisk aal = dutch_method(xx, yy) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeRisk.py", line 15, in dutch_method AAL = auc(yy, xx)+(xx[0]*yy[0]) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 97, in auc raise ValueError("x is neither increasing nor decreasing " ValueError: x is neither increasing nor decreasing : [0.02 0.05 0.01].Traceback (most recent call last): File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task R = retval = fun(*args, **kwargs) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__ return self.run(*args, **kwargs) File "/opt/sdss/django/sdss/risk/tasks.py", line 143, in risk_calculation_with_celery risk_calculation(risk_id) File "/opt/sdss/django/sdss/risk/tasks.py", line 69, in risk_calculation ComputeRisk(CONN_STR, loss_id, risk_id) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeRisk.py", line 73, in ComputeRisk risk = calculateRisk(lossdf, columns, probs) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeRisk.py", line 56, in calculateRisk aal = dutch_method(xx, yy) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeRisk.py", line 15, in dutch_method AAL = auc(yy, xx)+(xx[0]*yy[0]) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 97, in auc raise ValueError("x is neither increasing nor decreasing " ValueError: x is neither increasing nor decreasing : [0.02 0.05 0.01].
````
