### ISSUE TITLE
Landslide loss not woking

### ISSUE THREAD

**Issue by shakyaanice** [ashokdahal/RiskChanges#50]
```
Traceback (most recent call last):
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/sdss/django/sdss/loss/views.py", line 100, in create
    loss_calculation(loss_id)
  File "/opt/sdss/django/sdss/loss/tasks.py", line 26, in loss_calculation
    ComputeLoss(CONN_STR, exposure_id, loss_id, loss_type)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeLoss.py", line 100, in ComputeLoss
    loss = calculateLoss(exposure, costColumn, spprob)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeLoss.py", line 52, in calculateLoss
    exposuretable['loss'] = exposuretable.apply(
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/frame.py", line 7768, in apply
    return op.get_result()
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/apply.py", line 185, in get_result
    return self.apply_standard()
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/apply.py", line 276, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/apply.py", line 290, in apply_series_generator
    results[i] = self.f(v)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeLoss.py", line 53, in <lambda>
    lambda row: row[costColumn]*row.exposed*row.vuln*spprob/100, axis=1)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)

Exception Type: AttributeError at /api/loss/
Exception Value: 'Series' object has no attribute 'vuln'
Request information:
```

**Comment by ashokdahal** [comment]
This issue is fixed by update. Once @iamtekson integrates please check again for the performance.

**Comment by iamtekson** [comment]
I just updated the code in server @ashokdahal, @shakyaanice

**Comment by shakyaanice** [comment]
```
Traceback (most recent call last):
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 1697, in execute
    cur.execute(*args, **kwargs)

The above exception (column "none" does not exist
LINE 1: ...vulvalues" as vulntable WHERE vulntable."vulnID_fk_id"=None;
                                                                  ^
) was the direct cause of the following exception:
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/sdss/django/sdss/loss/views.py", line 100, in create
    loss_calculation(loss_id)
  File "/opt/sdss/django/sdss/loss/tasks.py", line 26, in loss_calculation
    ComputeLoss(CONN_STR, exposure_id, loss_id, loss_type)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeLoss.py", line 87, in ComputeLoss
    exposure = estimatevulnerability(exposure, haztype, vulnColumn, con)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/ComputeLoss.py", line 22, in estimatevulnerability
    vulnerbaility = readSusVuln(con, i)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/RiskChangesOps/readvulnerability.py", line 24, in readSusVuln
    vulntable=pd.read_sql(sql_val,engine)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 484, in read_sql
    return pandas_sql.read_query(
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 1743, in read_query
    cursor = self.execute(*args)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 1709, in execute
    raise ex from exc

Exception Type: DatabaseError at /api/loss/
Exception Value: Execution failed on sql 'SELECT * FROM public."projectIndex_vulvalues" as vulntable WHERE vulntable."vulnID_fk_id"=None;': column "none" does not exist
LINE 1: ...vulvalues" as vulntable WHERE vulntable."vulnID_fk_id"=None;
                                                                  ^
```

**Comment by shakyaanice** [comment]
I first tried by editing the vulnerability connection of the existing EAR layer, it showed the same error. Then I added a new EAR layer with landslide vulnerability connected and it showed this error.

**Comment by iamtekson** [comment]
I think #84 solved this issue.
