### ISSUE TITLE
Exposure with aggregation issues

### ISSUE THREAD

**Issue by shakyaanice** [ashokdahal/RiskChanges#51]
```
Traceback (most recent call last):
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
return self.dispatch(request, *args, **kwargs)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
response = self.handle_exception(exc)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
self.raise_uncaught_exception(exc)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
raise exc
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
response = handler(request, *args, **kwargs)
File "/opt/sdss/django/sdss/exposure/views.py", line 122, in create
exposure_calculation(exposure_id)
File "/opt/sdss/django/sdss/exposure/tasks.py", line 24, in exposure_calculation
ComputeExposure(conn_str, ear_id, hazard_id, exposure_id,
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/computeExposure.py", line 184, in ComputeExposure
df = aggregator.aggregateexpoure(df, admin_unit, adminpk)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/RiskChangesOps/AggregateData.py", line 7, in aggregateexpoure
overlaid_Data = gpd.overlay(
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/geopandas/tools/overlay.py", line 246, in overlay
if not _check_crs(df1, df2):
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/geopandas/array.py", line 85, in _check_crs
if not left.crs == right.crs:
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/generic.py", line 5465, in __getattr__
return object.__getattribute__(self, name)



Exception Type: AttributeError at /api/exposure/exposure/
Exception Value: 'DataFrame' object has no attribute 'crs'
```

**Comment by shakyaanice** [comment]
Second attempt by Tek but it showed a new error.
```
Traceback (most recent call last):
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1257, in _execute_context
self.dialect.do_executemany(
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 873, in do_executemany
cursor.executemany(statement, parameters)



The above exception (column "wo61k" of relation "exposure_result_agg" does not exist
LINE 1: ...SERT INTO anish_organization.exposure_result_agg (wo61k, cla...
^
) was the direct cause of the following exception:
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
return self.dispatch(request, *args, **kwargs)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
response = self.handle_exception(exc)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
self.raise_uncaught_exception(exc)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
raise exc
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
response = handler(request, *args, **kwargs)
File "/opt/sdss/django/sdss/exposure/views.py", line 122, in create
exposure_calculation(exposure_id)
File "/opt/sdss/django/sdss/exposure/tasks.py", line 24, in exposure_calculation
ComputeExposure(conn_str, ear_id, hazard_id, exposure_id,
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/computeExposure.py", line 187, in ComputeExposure
writevector.writeexposureAgg(df, con, schema)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/RiskChangesOps/writevector.py", line 19, in writeexposureAgg
df.to_sql('exposure_result_agg', engine, schema,
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/generic.py", line 2779, in to_sql
sql.to_sql(
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 590, in to_sql
pandas_sql.to_sql(
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 1405, in to_sql
raise err
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 1397, in to_sql
table.insert(chunksize, method=method)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 831, in insert
exec_insert(conn, keys, chunk_iter)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 748, in _execute_insert
conn.execute(self.table.insert(), data)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
return meth(self, multiparams, params)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_clauseelement
ret = self._execute_context(
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
self._handle_dbapi_exception(
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
util.raise_(
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
raise exception
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1257, in _execute_context
self.dialect.do_executemany(
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 873, in do_executemany
cursor.executemany(statement, parameters)



Exception Type: ProgrammingError at /api/exposure/exposure/
Exception Value: (psycopg2.errors.UndefinedColumn) column "wo61k" of relation "exposure_result_agg" does not exist
LINE 1: ...SERT INTO anish_organization.exposure_result_agg (wo61k, cla...
^



[SQL: INSERT INTO anish_organization.exposure_result_agg (wo61k, class, "exposed_areaOrLen", exposed, exposure_id) VALUES (%(wo61k)s, %(class)s, %(exposed_areaOrLen)s, %(exposed)s, %(exposure_id)s)]
[parameters: ({'wo61k': 0, 'class': 1.0, 'exposed_areaOrLen': 82815.42526828224, 'exposed': 1305, 'exposure_id': 191}, {'wo61k': 0, 'class': 2.0, 'exposed_areaOrLen': 13422.740143840583, 'exposed': 291, 'exposure_id': 191}, {'wo61k': 0, 'class': 3.0, 'exposed_areaOrLen': 7665.2794223529145, 'exposed': 178, 'exposure_id': 191}, {'wo61k': 0, 'class': 4.0, 'exposed_areaOrLen': 5837.947083350871, 'exposed': 126, 'exposure_id': 191}, {'wo61k': 0, 'class': 5.0, 'exposed_areaOrLen': 2948.17531677022, 'exposed': 71, 'exposure_id': 191}, {'wo61k': 0, 'class': 6.0, 'exposed_areaOrLen': 4339.107236242886, 'exposed': 87, 'exposure_id': 191}, {'wo61k': 0, 'class': 7.0, 'exposed_areaOrLen': 3545.78628726862, 'exposed': 88, 'exposure_id': 191}, {'wo61k': 0, 'class': 8.0, 'exposed_areaOrLen': 4498.340249456277, 'exposed': 100, 'exposure_id': 191} ... displaying 10 of 99 total bound parameter sets ... {'wo61k': 11, 'class': 9.0, 'exposed_areaOrLen': 635.9779515219527, 'exposed': 23, 'exposure_id': 191}, {'wo61k': 11, 'class': 10.0, 'exposed_areaOrLen': 735.6631533131265, 'exposed': 29, 'exposure_id': 191})]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by ashokdahal** [comment]
This error is caused by not renaming the admin unit column primary key.. I will rename it and fix it to one.. BTW, can we check what are the aggregated results column names are?

**Comment by ashokdahal** [comment]
@iamtekson @shakyaanice could you please put the name of the columns for exposure_result_agg table here? so that I can add exactly matching column names.. Because we added admin unit names instead of geom_id, the results are not being stored there.

**Comment by iamtekson** [comment]
The name of the column for aggregation is `col_admin` from the adminUnit table, [github.com/RiskChanges/riskchanges-backend/blob/master/sdss/projectIndex/models.py#L86](https://github.com/RiskChanges/riskchanges-backend/blob/master/sdss/projectIndex/models.py#L86)

**Comment by shakyaanice** [comment]
When computed with aggregation, it gave weird results in exposure and loss
![loss_admin](https://user-images.githubusercontent.com/58799032/151739358-2ad94085-a996-4481-b11c-76f67e0c2a0a.jpg)
![exposure_admin](https://user-images.githubusercontent.com/58799032/151739362-599e5283-d411-42db-b768-5dc31d5d5469.jpg)
.

**Comment by iamtekson** [comment]
The issue is duplicated to #71. We can close this issue.
