### ISSUE TITLE
OGC Upload Error

### ISSUE THREAD

**Issue by shakyaanice** [ashokdahal/RiskChanges#67]
```
Traceback (most recent call last):
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/sdss/django/sdss/projectIndex/views.py", line 78, in create
    self.perform_create(serializer)
  File "/opt/sdss/django/sdss/projectIndex/views.py", line 163, in perform_create
    serializer.save(organization=self.request.user.organization,
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/serializers.py", line 948, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/sdss/django/sdss/projectIndex/models.py", line 184, in save
    super(EarIndex, self).save(*args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/db/models/base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/db/models/base.py", line 793, in save_base
    post_save.send(
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/sdss/django/sdss/projectIndex/signals.py", line 25, in get_file_size
    file = instance.file.path
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/db/models/fields/files.py", line 56, in path
    self._require_file()
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/db/models/fields/files.py", line 38, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)

Exception Type: ValueError at /api/projectindex/ear/
Exception Value: The 'file' attribute has no file associated with it.

```

**Comment by iamtekson** [comment]
Solved! Need to update on server.
