### ISSUE TITLE
Error during aggregation in exposure

### ISSUE THREAD

**Issue by shakyaanice** [ashokdahal/RiskChanges#71]
```
Traceback (most recent call last):
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1257, in _execute_context
    self.dialect.do_executemany(
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 873, in do_executemany
    cursor.executemany(statement, parameters)

The above exception (column "arvl9" of relation "exposure_result_agg" does not exist
LINE 1: ...iskchanges_demo_organization.exposure_result_agg (arvl9, cla...
                                                             ^
) was the direct cause of the following exception:
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/sdss/django/sdss/exposure/views.py", line 284, in create
    exposure_calculation(exposure_id)
  File "/opt/sdss/django/sdss/exposure/tasks.py", line 36, in exposure_calculation
    ComputeExposure(conn_str, ear_id, hazard_id, exposure_id,
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/computeExposure.py", line 187, in ComputeExposure
    writevector.writeexposureAgg(df, con, schema)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/RiskChangesOps/writevector.py", line 19, in writeexposureAgg
    df.to_sql('exposure_result_agg', engine, schema,
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/generic.py", line 2779, in to_sql
    sql.to_sql(
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 590, in to_sql
    pandas_sql.to_sql(
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 1405, in to_sql
    raise err
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 1397, in to_sql
    table.insert(chunksize, method=method)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 831, in insert
    exec_insert(conn, keys, chunk_iter)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/io/sql.py", line 748, in _execute_insert
    conn.execute(self.table.insert(), data)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1257, in _execute_context
    self.dialect.do_executemany(
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 873, in do_executemany
    cursor.executemany(statement, parameters)

Exception Type: ProgrammingError at /api/exposure/exposure/
Exception Value: (psycopg2.errors.UndefinedColumn) column "arvl9" of relation "exposure_result_agg" does not exist
LINE 1: ...iskchanges_demo_organization.exposure_result_agg (arvl9, cla...

```

**Comment by iamtekson** [comment]
```shell
Traceback (most recent call last):
  File "F:\SDSS\1. code\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "F:\SDSS\1. code\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\SDSS\1. code\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\SDSS\1. code\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "F:\SDSS\1. code\venv\lib\site-packages\rest_framework\viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\SDSS\1. code\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "F:\SDSS\1. code\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "F:\SDSS\1. code\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "F:\SDSS\1. code\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\SDSS\1. code\django\sdss\exposure\views.py", line 309, in create
    exposure_calculation(exposure_id)
  File "F:\SDSS\1. code\django\sdss\exposure\tasks.py", line 36, in exposure_calculation
    ComputeExposure(conn_str, ear_id, hazard_id, exposure_id,
  File "F:\SDSS\1. code\venv\lib\site-packages\RiskChanges\computeExposure.py", line 194, in ComputeExposure
    overlaid_Data = gpd.overlay(df, admin_unit[[adminpk, 'geom']], how='intersection', make_valid=True, keep_geom_type=True)
  File "F:\SDSS\1. code\venv\lib\site-packages\geopandas\tools\overlay.py", line 253, in overlay
    if not _check_crs(df1, df2):
  File "F:\SDSS\1. code\venv\lib\site-packages\geopandas\array.py", line 68, in _check_crs
    if not left.crs == right.crs:
  File "F:\SDSS\1. code\venv\lib\site-packages\pandas\core\generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'crs'
```

**Comment by iamtekson** [comment]
Work on progress
```shell
Traceback (most recent call last):
  File "F:\SDSS\1. code\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "F:\SDSS\1. code\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\SDSS\1. code\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\SDSS\1. code\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "F:\SDSS\1. code\venv\lib\site-packages\rest_framework\viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\SDSS\1. code\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "F:\SDSS\1. code\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "F:\SDSS\1. code\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "F:\SDSS\1. code\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\SDSS\1. code\django\sdss\exposure\views.py", line 309, in create
    exposure_calculation(exposure_id)
  File "F:\SDSS\1. code\django\sdss\exposure\tasks.py", line 36, in exposure_calculation
    ComputeExposure(conn_str, ear_id, hazard_id, exposure_id,
  File "F:\SDSS\1. code\venv\lib\site-packages\RiskChanges\computeExposure.py", line 207, in ComputeExposure
    df['value'] = df['exposed'] * df['value']/100
  File "F:\SDSS\1. code\venv\lib\site-packages\pandas\core\frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "F:\SDSS\1. code\venv\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'value'
```

**Comment by iamtekson** [comment]
Now exposure table will look like this,

![image](https://user-images.githubusercontent.com/39838116/170194154-bbecb9ca-f71a-41d1-b770-007f3592f8e7.png)
