### ISSUE TITLE
Exposure id doesn't exist

### ISSUE THREAD

**Issue by iamtekson** [ashokdahal/RiskChanges#73]
I checked in the database, and the exposure id 270 is available, but here it shows not exist.

```sh
Traceback (most recent call last):
  File "F:\SDSS\1. code\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "F:\SDSS\1. code\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\SDSS\1. code\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\SDSS\1. code\django\sdss\exposure\views.py", line 31, in exposure_summary
    res = getSummary(CONN_STR, pk)
  File "F:\SDSS\1. code\venv\lib\site-packages\RiskChanges\getExposure.py", line 10, in getSummary
    metadata = readmeta.computeloss_meta(con, exposureid)
  File "F:\SDSS\1. code\venv\lib\site-packages\RiskChanges\RiskChangesOps\readmeta.py", line 64, in computeloss_meta
    meta=exposuremeta(connstr,exposureid)
  File "F:\SDSS\1. code\venv\lib\site-packages\RiskChanges\RiskChangesOps\readmeta.py", line 47, in exposuremeta
    assert not metatable.empty , f"The exposure id {exposureid} do not exists"
AssertionError: The exposure id 270 do not exists
```

**Comment by iamtekson** [comment]
Sorry I confused with hazard index.
