### ISSUE TITLE
Exposure issue still persist

### ISSUE THREAD

**Issue by shakyaanice** [ashokdahal/RiskChanges#79]
```
Request Method: POST
Request URL: http://203.159.29.45:8000/api/exposure/exposure/



Django Version: 3.2
Python Version: 3.8.10
Installed Applications:
['django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'django_extensions',
'rest_framework',
'django_rest_passwordreset',
'knox',
'corsheaders',
'accounts',
'organization.apps.OrganizationConfig',
'projectIndex.apps.ProjectindexConfig',
'options',
'style',
'introduction',
'services',
'exposure.apps.ExposureConfig',
'loss.apps.LossConfig',
'risk',
'django_celery_results',
'celery_progress',
'task.apps.TaskConfig',
'django_filters',
'django_cleanup.apps.CleanupConfig']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.security.SecurityMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware']





Traceback (most recent call last):
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
return self.dispatch(request, *args, **kwargs)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
response = self.handle_exception(exc)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
self.raise_uncaught_exception(exc)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
raise exc
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)
File "/opt/sdss/django/sdss/exposure/views.py", line 365, in create
exposure_calculation(exposure_id)
File "/opt/sdss/django/sdss/exposure/tasks.py", line 40, in exposure_calculation
ComputeExposure(conn_str, ear_id, hazard_id,
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/computeExposure.py", line 207, in ComputeExposure
df = df[default_cols]
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/geopandas/geodataframe.py", line 1327, in __getitem__
result = super().__getitem__(key)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/frame.py", line 3030, in __getitem__
indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/indexing.py", line 1266, in _get_listlike_indexer
self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/indexing.py", line 1316, in _validate_read_indexer
raise KeyError(f"{not_found} not in index")



Exception Type: KeyError at /api/exposure/exposure/
Exception Value: "[''] not in index"
```

**Comment by iamtekson** [comment]
Solved!
