### ISSUE TITLE
Exposure aggregation not working

### ISSUE THREAD

**Issue by shakyaanice** [ashokdahal/RiskChanges#80]
```
Traceback (most recent call last):
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/sdss/django/sdss/exposure/views.py", line 365, in create
    exposure_calculation(exposure_id)
  File "/opt/sdss/django/sdss/exposure/tasks.py", line 36, in exposure_calculation
    ComputeExposure(conn_str, ear_id, hazard_id, exposure_id,
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/RiskChanges/computeExposure.py", line 224, in ComputeExposure
    df = df[default_cols]
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/geopandas/geodataframe.py", line 1327, in __getitem__
    result = super().__getitem__(key)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/indexing.py", line 1266, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pandas/core/indexing.py", line 1316, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")

Exception Type: KeyError at /api/exposure/exposure/
Exception Value: "['admin_id'] not in index"
```

**Comment by iamtekson** [comment]
I think you forgot to add the column for admin unit.

**Comment by shakyaanice** [comment]
I  added as you recommended but still have the same issue as above. It works for non aggregated exposure though.

**Comment by iamtekson** [comment]
Finally solved. The issue here was, the column for `admin` is similar to one of the `ear` column. Now I rename the `ear` column name to `{admin_col}_ear`
