### ISSUE TITLE
Landslide loss

### ISSUE THREAD

**Issue by shakyaanice** [ashokdahal/RiskChanges#98]
Traceback (most recent call last): File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task R = retval = fun(*args, **kwargs) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__ return self.run(*args, **kwargs) File "/opt/sdss/django/sdss/loss/tasks.py", line 116, in loss_calculation_with_celery loss_calculation(loss_id) File "/opt/sdss/django/sdss/loss/tasks.py", line 95, in loss_calculation style = pySLD_class.generate_classified_style(values) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pysld/style.py", line 312, in generate_classified_style return self.classified_style() File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pysld/classifiedStyle.py", line 117, in classified_style self.choose_classification_method() File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pysld/classification.py", line 112, in choose_classification_method self.classes = self.jenks_breaks() File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/pysld/classification.py", line 45, in jenks_breaks return jenkspy.jenks_breaks(self.values, self.number_of_class) File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/jenkspy/core.py", line 107, in jenks_breaks raise ValueError("Number of class have to be an integer " ValueError: Number of class have to be an integer greater than 2 and smaller than the number of values to use

{"exc_type": "ValueError", "exc_message": ["Number of class have to be an integer greater than 2 and smaller than the number of values to use"], "exc_module": "builtins"}

**Comment by ashokdahal** [comment]
This is problem caused by symbology and styling may be @iamtekson or @rabinatwayana  solve the pysld problem?
