### ISSUE TITLE
Riskchanges visualization issue

### ISSUE THREAD

**Issue by iamtekson** [ashokdahal/RiskChanges#99]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/backend/exposure/views.py", line 63, in exposure_summary
    df = getSummary(CONN_STR, pk, column=exposed, agg=True)
  File "/usr/local/lib/python3.8/site-packages/RiskChanges/getExposure.py", line 17, in getSummary
    classificationScheme = readmeta.classificationscheme(con, hazid)
  File "/usr/local/lib/python3.8/site-packages/RiskChanges/RiskChangesOps/readmeta.py", line 23, in classificationscheme
    assert not classtable.empty , f"The classification scheme for hazard id  {hazid} do not exists"

Exception Type: AssertionError at /api/exposure/exposure/summary
Exception Value: The classification scheme for hazard id  927 do not exists

```

**Comment by iamtekson** [comment]
This error persist in `download exposure` section as well.
